# Generated by Django 2.2.5 on 2019-09-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='address10',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='address2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='address3',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='address4',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='address5',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='address6',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='address7',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='address8',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='address9',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='email10',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='email2',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='email3',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='email4',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='email5',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='email6',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='email7',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='email8',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='email9',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='phone10',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='phone2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='phone3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='phone4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='phone5',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='phone6',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='phone7',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='phone8',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='phone9',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
